version: '3.8'

services:

  node-app:
    build: ./node
    image: riyadrb/node-app
    ports:
      - '3000:3000'
    volumes:
      - node-data:/app/data
  
  python-app:
    build: ./python-app
    image: riyadrb/python-app
    ports:
      - '8000:8000'
    volumes:
      - python-data:/app/data

  java-app:
    build: ./demo
    image: riyadrb/maven
    ports:
      - '8080:8080'
    volumes:
      - java-data:/app/data

volumes:
  node-data:
  python-data:
  java-data:



