version: '3.8'

services:

  node-app:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - node-app-data:/app/data
  
  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - python-app-data:/app/data

  java-app:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - java-app-data:/app/data

volumes:
  node-app-data:
  python-app-data:
  java-app-data:



